### ISSUE TITLE
Please add @bmannand @cdata as owners on this repo

### ISSUE THREAD

**Issue by bmann** [ucan-wg/ucan-community-web#47]
@bgins thanks!

**Comment by zeeshanlakhani** [comment]
Probably worth a CODEOWNERS file on this, as it's not there: https://github.com/ucan-wg/ucan-check/tree/main/.github

**Comment by bgins** [comment]
> Probably worth a CODEOWNERS file on this, as it's not there: https://github.com/ucan-wg/ucan-check/tree/main/.github

Yeah, good idea! Re-opening this issue and we can add that.

**Comment by bgins** [comment]
Closed by #68
